
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: autospace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/autospace
    ports:
      - "3000:3000"
volumes:
  db_data:
